name: Feature request
description: Ideas for new sensors, events or improvements
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: What problem would it solve?
